CREATE TABLE blog.Post
(
	ID SERIAL,
	Title VARCHAR(1000) NOT NULL DEFAULT 'Untitled',
	Content TEXT NOT NULL DEFAULT '',
	creator_id INT NOT NULL,
	tags JSONB NOT NULL DEFAULT '[]'::jsonb,
	PRIMARY KEY(ID),
	FOREIGN KEY(creator_id) REFERENCES blog.users(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
)
